[package]
name = "backfat"
version = "0.1.1"
authors = ["the_r"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lopdf = "0.23.0"
lazy_static = "1.4.0"
rand = "0.7.3"